// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnTpAX9GRiSxnsast1yVvpThGKjYCeYlU',
    appId: '1:461195961076:web:60826419f44e2b46c174a1',
    messagingSenderId: '461195961076',
    projectId: 'fir-r1-e39b6',
    authDomain: 'fir-r1-e39b6.firebaseapp.com',
    storageBucket: 'fir-r1-e39b6.appspot.com',
    measurementId: 'G-ZPSW6S2XMM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCgRD-xWo-o4TWIGllUSsgtuc45zIWKVWU',
    appId: '1:461195961076:android:2e856f43e412fc6fc174a1',
    messagingSenderId: '461195961076',
    projectId: 'fir-r1-e39b6',
    storageBucket: 'fir-r1-e39b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeC76NuFtjNKsEMoXvFSCCDg7K9NuEJGw',
    appId: '1:461195961076:ios:ca0398227b8b0f20c174a1',
    messagingSenderId: '461195961076',
    projectId: 'fir-r1-e39b6',
    storageBucket: 'fir-r1-e39b6.appspot.com',
    iosBundleId: 'com.example.firebaseR1',
  );
}
